spring.application.name=hirepilot-jobs
server.port=8084
management.endpoints.web.exposure.include=health,info
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
