spring.application.name=hirepilot-candidate
server.port=8082
management.endpoints.web.exposure.include=health,info
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
