spring.application.name=hirepilot-integration
server.port=8087
management.endpoints.web.exposure.include=health,info
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
