spring.application.name=hirepilot-auth
server.port=8081
management.endpoints.web.exposure.include=health,info
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
