spring.application.name=hirepilot-search
server.port=8086
management.endpoints.web.exposure.include=health,info
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
